targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**.codegen.dart
        options:
          copy_with: false
          equal: false
          from_json: false
          to_json: false
          to_string_override: false
          map:
            map: false
            map_or_null: false
            maybe_map: false
          when:
            when: false
            when_or_null: false
            maybe_when: false